#!/bin/bash

if [ "$#" -lt 1 ]; then
    echo "Paramètre absent, merci d'indiquer le nom d'un container docker pour utiliser son CLI"
    exit
fi

id=$(docker ps -aqf "name=^/$1$")
sudo docker exec -it $id bash